import { Poppins, Caveat } from "next/font/google";
import "./globals.css";

// contexts
import EventProvider from "@/contexts/EventContext";
import TicketProvider from "@/contexts/TicketContext";

// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";

export const metadata = {
  title: "Event Horizont",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const caveat = Caveat({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-caveat",
});

export default function RootLayout({ children }) {
  return (
    <EventProvider>
      <TicketProvider>
        <html lang = "en">
          <body className = {`${poppins.variable} ${caveat.variable} antialiased`}>
            <Header />
            {children}
            <Footer />
            <ScrollToTop />
          </body>
        </html>
      </TicketProvider>
    </EventProvider>
  );
}